# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information
site_name: 光景录
site_url: https://txt.mone.moe/
site_author: 百音
site_description: >-
  Lets tell a story with Mone ✨

# Repository
# repo_name: txt
# repo_url: https://github.com/kurimone/txt
# edit_uri: edit/main/docs/

# Copyright
copyright: 版权所有 &copy; 2019 - 2025 百音.

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 换为浅色
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/brightness-7
        name: 跟随系统
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 换为深色
  language: zh
  font:
    text: Noto Serif SC
    code: Roboto Mono
  favicon: material/comma-circle
  icon:
    logo: material/comma-circle

# Plugins
plugins:
  - tags:
      enabled: false
      tags_file: archives.md
  - blog:
      enabled: false
      blog_dir: blog
  - rss:
      enabled: false
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - search:
      enabled: true
      lang:
        - zh
        - en
      # separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      # skip_classes:
      #   - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  # - redirects:
  #     redirect_maps:
  #       "parawiki/index.md": "parawiki/comming-soon.md"
  - git-revision-date-localized:
      enabled: true
      type: date
      timezone: Asia/Shanghai
      locale: zh

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kurimone
    - icon: fontawesome/solid/paper-plane
      link: mailto:m@mone.moe
  generator: false

# Additional stylesheet
extra_css:
  - assets/stylesheets/extra.css

# Additional javascript
extra_javascript:
  - assets/javascripts/extra.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: KURiMONE
      repo: txt
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 序: index.md
  # - 留言板: comment.md
  # - 只言:
  #   - 10.md
  #   - 9.md
  #   - 8.md
  #   - 7.md
  #   - 2.md
