name: Deploy Docs

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Deploy to GitHub Pages
      run: poetry run mkdocs gh-deploy --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          SERVER_PATH="${{ secrets.SERVER_PATH }}"
          REPO_URL="https://github.com/kurimone/txt.git"
          REPO_BRANCH="gh-pages"
          
          if [ -d "$SERVER_PATH/.git" ]; then
            echo "🔄 Repository exists, updating..."
            cd "$SERVER_PATH"
            git reset --hard HEAD
            git pull
          else
            echo "🆕 Cloning new repository..."
            mkdir -p "$(dirname "$SERVER_PATH")"
            rm -rf "$SERVER_PATH"/*
            git clone -b "$REPO_BRANCH" "$REPO_URL" "$SERVER_PATH"
          fi

          chmod -R 755 "$SERVER_PATH"
